# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '407731d6-d702-4a99-b7ea-a3a166c3d5c7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'tyangRG'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName tyangpipeline -linkedTemplateUri https://github.com/tyang0223/AzureRmPipeline/blob/master/CreateWebApp/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'